## model.py
## Author: Yangfeng Ji
## Date: 09-09-2014
## Time-stamp: <yangfeng 09/13/2014 17:50:57>

""" As a parsing model, the main function is to determine
    the parsing action for a given set of features
"""

from sklearn.svm import LinearSVC

class ParsingModel(object):
    def __init__(self, vocab=None):
        """ Initialization
        """
        self.vocab = vocab
        self.model = LinearSVC()


    def train(self, trnM, trnL):
        """ Perform batch-learning on parsing model
        """
        self.model.fit(trnM, trnL)


    def predict(self, features):
        """ Predict parsing actions for a given set
            of features

        :type features: list
        :param features: feature list generated by
                         FeatureGenerator
        """
        vec = self.__vectorize(features)
        label = self.model.predict(vec)
        return label


    def __vectorize(self, features):
        """ Transform a set of features into one vector
        :type features: list
        :param features:
        """
        return vectorize(features, self.vocab)
